stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: maven:3-adoptopenjdk-11
          shellScript: mvn package -DskipTests
  - name: Build Docker with DIND
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: docker.dev.folio.org/mod-feesfines:vega-master-dev
          pushRemote: true
          registry: docker.dev.folio.org
  - name: Deploy
    steps:
      - applyAppConfig:
          catalogTemplate: p-wntj9:vega-helmcharts-mod-feesfines
          version: 0.1.26
          answers:
            image.repository: docker.dev.folio.org/mod-feesfines
            image.tag: vega-master-dev
          name: mod-feesfines
          targetNamespace: vega
timeout: 60
notification: {}